### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by dail** [papandreou/subset-font#1]
when call  the subset method much times, it will crashed with memory leak.

#https://github.com/harfbuzz/harfbuzzjs/issues/36

**Comment by papandreou** [comment]
Thanks for tracking that down and reporting it 🙇 

Let's wait and see how the harfbuzzjs issue plays out. Happy to accept a PR here once a fix it out!

**Comment by papandreou** [comment]
Fixed in 1170630a1cb3be4a5279facc75cecfd5220ede1f, released in 1.1.2 😌
