### ISSUE TITLE
Subsetting a Arabic font doesn't seem to work

### ISSUE THREAD

**Issue by mirkovw** [papandreou/subset-font#17]
Hi there! 

So we're running in to a problem with subsetting arabic fonts.

Using this code:
```
const subsetFont = require('subset-font');
const fs = require('fs').promises;

(async function () {

    const font = await fs.readFile('./fonts/Farah.woff');
    const fontBuffer = Buffer.from(font);

    const subset = await subsetFont(fontBuffer, 'المستقبل', {
        targetFormat: 'woff',
    });

    await fs.writeFile('./fonts/Farah-Optimized.woff', subset)

})();
```

And here's the result

![image](https://user-images.githubusercontent.com/17322220/170085752-2bbb77c9-3d38-4667-b2dd-0cf76143b86c.png)
(top is unchanged font, bottom is the subset)

The bottom text, when checked in the dev inspector, shows that it is actually rendering Arial (fall back), and not Farah.
Font direction in css has also been set to 'rtl', although not sure if it matters in this case.

Is this a known issue? 

Let me know if you need any more info!
Thanks

**Comment by papandreou** [comment]
Hmm, no, that's not a known problem 😅 

First off, can you get it to work if you create the subset font using `pyftsubset` from https://github.com/fonttools/fonttools instead?

**Comment by mirkovw** [comment]
Hi @papandreou , thanks for replying!

I've gone ahead and done a quick test with `pyftsubset` like you suggested, using the following code

```
import sys
from fontTools.subset import main as ss
sys.argv = [None, 'fonts/Farah.woff', '--text=المستقبل', '--output-file=fonts/Farah-optimized-python.woff']
ss()
```

Same result, unfortunately.

However I have noticed that including all characters, for example through

`sys.argv = [None, 'fonts/Farah.woff', '--unicodes=*', '--output-file=fonts/Farah-optimized-python.woff']`

This will result in a font that works as intended. 

So it looks like we're simply missing essential characters in the subset.

Looking into Arabic fonts a bit, it looks like each glyph has multiple characters. The actual rendered character depends on its position in the word: start, middle, or end. Also, there might be special characters in Arabic fonts that serve as connectors between letters... sort of? It's fairly complex :)

This allows each word to be written in a connected flow, instead of separate characters like we see in English for example.

**Comment by papandreou** [comment]
Interesting! As far as I'm aware, both `pyftsubset` and the Harfbuzz subsetter try to include all the ligatures that are related to the characters in the subset. I wonder if that heuristic isn't enough for Arabic text? Not sure if that positional thing you're describing is even based on ligatures?

Might be worth it to take a look at the output of `ttx` on your original font vs. the subset, and try to "tease out" which codepoints have to be explicitly added for the web browser not to fall back.

**Comment by khaledhosny** [comment]
How did you obtain the font Farah? If it is the font bundled with macOS, this a font with AAT layout tables as opposed to OpenType, both FontTools and HarfBuzz don’t support subsetting AAT layout tables and they are probably dropping them. since they don’t support these tables, glyph closure will not work and you will get only the base glyphs for the characters you requested. Asking for all characters seem to work because now HarfBuzz (when laying out the text) will be doing fallback Arabic shaping based on Arabic Presentation Forms and for a simple font like this it is probably very close to the AAT shaping .

**Comment by khaledhosny** [comment]
If `ttx -l` shows a `morx` or `mort` table and no `GSUB` table, then this is indeed an AAT font.

**Comment by mirkovw** [comment]
Ahh I see, thank you!! I'll check it out.

**Comment by papandreou** [comment]
I'll close as there doesn't seem to be anything this module can do about the problem :innocent:
