### ISSUE TITLE
tnum font feature being stripped from Noto Sans

### ISSUE THREAD

**Issue by robinwhittleton** [papandreou/subset-font#24]
This is an odd one, but I’ve tried to eliminate everything else I can think of. I’ve attached a Noto Sans woff file to this issue:

[NotoSansLatin-Regular.woff.zip](https://github.com/user-attachments/files/16051810/NotoSansLatin-Regular.woff.zip)

This was prepared from the normal Noto Sans Latin Regular ttf by running it through [fonttools](https://github.com/fonttools/fonttools) to strip most font features and save it as a woff, leaving it with `liga`, `tnum`, `zero` and `kern`.

The next step in our pipeline is to subset it by running it through subset-font and export it as a woff2. The code for this is as simple as you’d expect:

```js
  const glyphs = glyphsFromUnicodeRange(unicodeRange);
  const result = await subsetFont(font, glyphs.join(''), {
    targetFormat: 'woff2',
    preserveNameIds: true
  });
```

At this point, the `tnum` feature is lost from the font.

This wasn’t an issue with the older version of Noto we were using (forked ~5 years ago), but has cropped up when upgrading to a newer version. I’ve tested various versions of subset-font back to 1.7.1 to see if it’s a recent bug, but no luck. Fonttools doesn’t seem to be the issue either, as excluding it from the pipeline doesn’t stop the `tnum` stripping from the subset-font command. My best guess is that the way `tnum` has been specified in Noto is now out of spec enough for harfbuzzjs or subset-font to trip on it.

I’ve been verifying the end state with https://wakamaifondue.com/beta/ so it’s I guess possible that there’s a bug there?

Any ideas?

(Side note: me or @bjrn should probably work on a `layoutFeatures` contribution to this project at some point so that we can skip our usage of fonttools entirely, but that’s a seperate issue.)

**Comment by papandreou** [comment]
Hmm, I think the issue might be that the Harfbuzz subsetter doesn't support this yet.

I can confirm that the font you provided does indeed contain a `tnum` feature tag:

```
$ ttx -o - testdata/NotoSansLatin-Regular.woff | grep FeatureTag
[...]
Dumping 'GPOS' table...
        <FeatureTag value="kern"/>
        <FeatureTag value="kern"/>
        <FeatureTag value="kern"/>
        <FeatureTag value="kern"/>
        <FeatureTag value="kern"/>
Dumping 'GSUB' table...
Dumping 'STAT' table...
        <FeatureTag value="liga"/>
        <FeatureTag value="tnum"/>
        <FeatureTag value="zero"/>
```

I can also confirm that it get stripped by `subset-font`. But trying to explicitly tell the harfbuzz subsetter to preserve it doesn't help:

```diff
diff --git a/index.js b/index.js
index b46f4e5..0386963 100644
--- a/index.js
+++ b/index.js
@@ -77,6 +77,12 @@ async function subsetFont(
     }
   }
 
+  const inputLayoutFeatureTags = exports.hb_subset_input_set(
+    input,
+    6 // HB_SUBSET_SETS_LAYOUT_FEATURE_TAG,
+  );
+  exports.hb_set_add(inputLayoutFeatureTags, HB_TAG('tnum'));
+
   if (noLayoutClosure) {
     exports.hb_subset_input_set_flags(
       input,
```

I tried compiling the [`hb-subset`](https://github.com/harfbuzz/harfbuzz/blob/main/util/hb-subset.cc) CLI tool, and unfortunately it seems to have the same issue, even when explicitly telling it to include the `tnum` feature:

```
$ ./build/util/hb-subset --layout-features+=tnum ../subset-font/testdata/NotoSansLatin-Regular.ttf --text=foobar0123456789 -o hbsubsetted.ttf
$ ttx -o - hbsubsetted.ttf
[...]
Dumping 'GPOS' table...
        <FeatureTag value="kern"/>
Dumping 'GSUB' table...
Dumping 'STAT' table...
        <FeatureTag value="liga"/>
```

You probably know more about `tnum` than I do. Does it look like I'm doing something wrong? At this point I'm not sure if the feature is missing from `hb-subset` (and thus isn't available for `subset-font` either), or if I'm making some kind of rookie mistake :thinking:

**Comment by robinwhittleton** [comment]
Thanks so much for spending the time to test and confirm, really appreciate it.

I agree that this is either a harfbuzz / hb-subset bug or an unexpected behaviour. So I’ll file an issue with them to see if we can resolve it one way or another.

**Comment by papandreou** [comment]
Great! Let me know what you find out and if/when there's something we can do in `subset-font` :sun_with_face:

**Comment by robinwhittleton** [comment]
As discussed on harfbuzz, the primary cause for my confusion turned out to be a bug in the original font, followed up by a secondary problem with fonttools 🤦‍♂️ This can be closed.

**Comment by papandreou** [comment]
I noticed that `subset-font` already hardcodes the equivalent of `--font-features=*` [here](https://github.com/papandreou/subset-font/blob/3f711c8aa29a426c7f22655861abfb976950f527/index.js#L62-L68), so we shouldn't need to change anything here unless we want to offer _stripping_ features.
