### ISSUE TITLE
Subsetting emojis from an emoji font results in a non-working font

### ISSUE THREAD

**Issue by Calinou** [papandreou/subset-font#26]
Using Node.js 23.1.0 on Windows 11 23H2, I've tried to subset a small number of emoji from [Noto Color Emoji](https://fonts.google.com/noto/specimen/Noto+Color+Emoji) which I've downloaded from Google Fonts. For context, I'm looking to address https://github.com/godotengine/godot-demo-projects/issues/1119 without committing a 24 MB file to that repository.

Using the following script:

```javascript
#!/usr/bin/env node
const fs = require('fs');
const subsetFont = require('subset-font');

const inputFile = 'NotoColorEmoji-Regular.ttf';
const outputFile = 'NotoColorEmoji-Regular-subset.woff2';
const subsetText = '🥳🧁🍰🎁🎂🎈🎺🎉🎊📧〽️🧿🌶️🔋😂❤️😍🤣😊🥺🙏💕😭😘👍😅👏';

const mySfntFontBuffer = Buffer.from(fs.readFileSync(inputFile));
(async () => {
  const subsetBuffer = await subsetFont(mySfntFontBuffer, subsetText, {
    targetFormat: 'woff2',
  });

  fs.writeFile(outputFile, subsetBuffer, 'binary', (err) => {
    if (!err) {
      console.log(`Subset written to: ${outputFile}`);
    } else {
      console.error(err);
    }
  });
})();
```

`package.json`:

```json
{
  "type": "commonjs",
  "dependencies": {
    "subset-font": "^2.4.0"
  }
}
```

The font generation process works, but the resulting font doesn't have working emoji, even though they are included in the font. You don't see emoji when trying to enter them using an emoji keyboard (or copy-pasting from a website listing emoji).

I've tried both WOFF2 and SFNT (`.ttf`) output to no avail.

[Wakamai Fondue](https://wakamaifondue.com/beta/) has this to say about the generated subset:

![image](https://github.com/user-attachments/assets/f672c838-64a8-434e-bbe3-d80897d69115)

![image](https://github.com/user-attachments/assets/2dbbcf59-2409-43d5-9675-51ac7555f30c)

The original TTF in comparison:

![image](https://github.com/user-attachments/assets/0c9b39bf-f87b-48a5-b231-6dfb6e1dec36)

Loading the original font in Godot 4.3:

![image](https://github.com/user-attachments/assets/ae2e40ad-9999-4dd0-a140-544fa52d51f0)

Loading either of the subset fonts:

![image](https://github.com/user-attachments/assets/04387f3c-c174-4c1a-a7a9-4df80f46c645)

**Comment by papandreou** [comment]
Can you confirm that the same subsetting works with `hb-subset`?

**Comment by Calinou** [comment]
> Can you confirm that the same subsetting works with `hb-subset`?

I've tried and it didn't work in Godot either.

[NotoColorEmoji-subset.zip](https://github.com/user-attachments/files/17612339/NotoColorEmoji-subset.zip)

Command line:

```
hb-subset NotoColorEmoji-Regular.ttf \
  --text="🥳🧁🍰🎁🎂🎈🎺🎉🎊📧〽️🧿🌶️🔋😂❤️😍🤣😊🥺🙏💕😭😘👍😅👏" \
  --output-file="NotoColorEmoji-Regular-subset.ttf"
```

However, [this is actually most likely a Godot bug](https://github.com/godotengine/godot-demo-projects/issues/1119#issuecomment-2444895898), so I'll close this for now.
